### PR TITLE
Add is_prime_biguint

### PR DESCRIPTION
**Pull request by sethbywater**
For libraries that already use `BigUint`s, it's easier if there's an interface to pass it directly instead of types that are `ToBigUint`

### CODE REVIEW

**Comment by sethbywater** [comment]
Fixes #1 
@z-tech I didn't see your issue before creating this PR and you've probably moved on, but here you go

**Comment by rj-calvin** [comment]
You're right. I had forgotten. I've been caught up in other projects! Thanks for the PR, looks simple enough for merge.

**Comment by rj-calvin** [comment]
By the way, I find it very odd that `ToBigInt` isn't implemented by `BigUInt` etc., I'd imagine that it would trivially be implemented by the identity function.

**Comment by rj-calvin** [comment]
I just looked it up. Apparently in `num-0.4.0` `ToBigInt` is implemented by `BigUInt`.

**Pull request merged**
