### PR TITLE
bumped num-bigint to 0.4 (#1)

### PR DESCRIPTION
**Pull request by rj-calvin**
bumped rand to 0.8

renamed `__miller_rabin` to `miller_rabin`

removed `is_prime_biguint`

### CODE REVIEW

**Comment by rj-calvin** [comment]
@sethbywater Hey, so I think that updating `num-bigint` to `0.4.0` resolves the issue for #1. I added a test case for the situation where one passes an instance of `BigUInt` to `is_prime` and it passes. Can you verify if this satisfies your use case?

**Comment by sethbywater** [comment]
@cjayross Yes, this works great and is much better than adding another function like I did

**Comment by patrobinson** [comment]
@cjayross this doesn't look to have been released as a crate yet. Are you able to?

**Comment by rj-calvin** [comment]
> @cjayross this doesn't look to have been released as a crate yet. Are you able to?

Oh, has it not been? I'll address that.

**Comment by rj-calvin** [comment]
@patrobinson Done. Sorry about that.

**Pull request merged**
