### PR TITLE
support single-threaded calculation

### PR DESCRIPTION
**Pull request by picoHz**
I want to use this crate for single-threaded calculation on WebAssembly.
This PR makes the rayon dependency optional.

### CODE REVIEW

**Comment by rj-calvin** [comment]
Will this change the default behavior of the library?

**Comment by picoHz** [comment]
No, it won’t. Since rayon feature is [specified as default-feature](https://github.com/cjayross/miller_rabin/pull/4/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R27), multithreading is enabled by default.

To use single-threaded mode, you need to explicitly disable the rayon feature like this:

```toml
miller_rabin = { version = "1.1.0", default-features = false }
```

**Comment by rj-calvin** [comment]
Cool deal. Approved.

**Comment by rj-calvin** [comment]
I'll create a release for it tomorrow.

**Pull request merged**
